version: "3.8"

services:
  Backend_Web-Manga:
    build: ./Backend_Web-Manga
    ports:
      - "4001:4001"
    networks:
      - mynetwork

  Frontend_Web-Manga:
    build: ./Frontend_Web-Manga
    ports:
      - "4000:80"
    depends_on:
      - Backend_Web-Manga
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
