version: "3.8"

services:
  backend:
    build: ./Backend_Web-Manga
    ports:
      - "4001:4001"
    networks:
      - mynetwork

  frontend:
    build: ./Frontend_Web-Manga
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
